METHOD GETTAG.

DATA: NODE   TYPE REF TO IF_IXML_NODE.

CALL METHOD XMLDOCUMENT->FIND_NODE
  EXPORTING
    NAME   = TAG
  RECEIVING
    NODE   = NODE.

    CALL METHOD NODE->GET_VALUE
        RECEIVING
          RVAL = VALOR.

ENDMETHOD.