METHOD XML_FROM_FILE.

DATA  RETSUB TYPE SY-SUBRC.
DATA: COMP   TYPE ZTBFLBIWSCOMP,
      CAD    TYPE TABLE OF ZTBFLBIWSINFCAD.

 CREATE OBJECT XMLDOCUMENT.

 CALL METHOD XMLDOCUMENT->IMPORT_FROM_FILE
   EXPORTING
     FILENAME = FILENAME
   RECEIVING
     RETCODE  = RETSUB.

*** Teste **
**DATA WK_INFCAD TYPE ZTBFLBIWSINFCAD.
**DATA INFCAD    TYPE TABLE OF ZTBFLBIWSINFCAD.
**
**FIELD-SYMBOLS: <CAD> TYPE ANY TABLE.
**               ASSIGN CAD TO <CAD>.
**
**     CALL METHOD ME->Z_IF_FL_BIWS_XML~PARSETOTABLE
**       EXPORTING
***         XMLIDOM =
**         XMLDOM  = XMLDOCUMENT
**       CHANGING
**         TBCOMP  = COMP
**         TBINF   = <CAD>.
**
**
**     BREAK-POINT.
*** Teste ***



ENDMETHOD.