method Z_IF_FL_BIWS_XML~PARSEDOMTOSTRING.

     DATA TEMPSTRING TYPE STRING.
     DATA RC TYPE SYSUBRC.
     DATA: RESULT_TAB TYPE TABLE OF STRING.

     CALL METHOD XMLDOM->RENDER_2_STRING
       EXPORTING
         PRETTY_PRINT = 'X'
       IMPORTING
         RETCODE      = RC
         STREAM       = TEMPSTRING.


    XMLSTRING = TEMPSTRING.

endmethod.