METHOD Z_IF_FL_BIWS_XML~PARSESTRINGTODOM.

  DATA XMLDOC TYPE REF TO CL_XML_DOCUMENT.
  DATA RET    TYPE SY-SUBRC.

  CREATE OBJECT XMLDOC.

  CALL METHOD XMLDOC->PARSE_STRING
    EXPORTING
      STREAM  = XMLSTRING
    RECEIVING
      RETCODE = RET.

      XMLDOM = XMLDOC.

ENDMETHOD.