METHOD Z_IF_FL_BIWS_XML~PARSESTRINGTOIDOM.

  DATA IXML TYPE REF TO IF_IXML.
  DATA STREAMFACTORY TYPE REF TO IF_IXML_STREAM_FACTORY.
  DATA ISTREAM TYPE REF TO IF_IXML_ISTREAM.
  DATA IXMLPARSER TYPE REF TO IF_IXML_PARSER.
  DATA XMLDOC TYPE REF TO IF_IXML_DOCUMENT.

    IXML = CL_IXML=>CREATE( ).
    XMLDOC = IXML->CREATE_DOCUMENT( ).
    STREAMFACTORY = IXML->CREATE_STREAM_FACTORY( ).
    ISTREAM = STREAMFACTORY->CREATE_ISTREAM_STRING( XMLSTRING ).
    IXMLPARSER = IXML->CREATE_PARSER(  STREAM_FACTORY = STREAMFACTORY
                                       ISTREAM        = ISTREAM
                                       DOCUMENT       = XMLDOC ).
    IXMLPARSER->PARSE( ).
    XMLIDOM = XMLDOC.

ENDMETHOD.